/*
 * app_sim3g.h
 *
 *  Created on: Nov 22, 2019
 *      Author: VAIO
 */


#ifndef APP_SIM3G_H_
#define APP_SIM3G_H_



typedef enum {
	SIM3G_STATUS = 0,
	WAIT_FOR_SIM3G_STATUS_RESPONSE,

	POWER_ON_SIM3G,
	WAIT_FOR_SIM3G_POWER_ON,
	POWER_OFF_SIM3G,
	WAIT_FOR_SIM3G_POWER_OFF,

	RESET_SIM3G,
	WAIT_FOR_SIM3G_RESET,

	APN_SETTING,
	WAIT_FOR_APN_SETTING_RESPONSE,
	DEFINE_TCPIP_CONTEXT,
	WAIT_FOR_DEFINE_TCPIP_CONTEXT_RESPONSE,
//	SET_AUTHENTICATION_PARAMETER,
//	WAIT_FOR_SET_AUTHENTICATION_PARAMETER_RESPONSE,
	SET_PDP_CONTEXT_NUMBER,
	WAIT_FOR_SET_PDP_CONTEXT_NUMBER_RESPONSE,
	COMMAND_MODE,
	WAIT_FOR_COMMAND_MODE_RESPONSE,
	NETOPEN,
	WAIT_FOR_NETOPEN_RESPONSE,
	IPCONFIG,
	WAIT_FOR_IPCONFIG_RESPONSE,
	NETCLOSE,
	WAIT_FOR_NETCLOSE_RESPONSE,
//	RECEIVE_DATA_LENGTH_OPTION,
//	WAIT_FOR_RECEIVE_DATA_LENGTH_OPTION_RESPONSE,
//	RECEIVE_DATA_ADDRESS_OPTION,
//	WAIT_FOR_RECEIVE_DATA_ADDRESS_OPTION_RESPONSE,
//	ADJUST_NUMBER_OF_RETRANSMISSION,
//	WAIT_FOR_ADJUST_NUMBER_OF_RETRANSMISSION_RESPONSE,

	MAX_NUMBER_STATES
}SIM3G_STATE;


typedef struct {
	SIM3G_STATE state;
	void (*func)(void);
}Sim3g_Machine_Type;




void Sim3g_Init(void);
void Sim3g_Run(void);
void Set_Sim3G_State(SIM3G_STATE newState);
SIM3G_STATE Get_Sim3G_State(void);

#endif /* APP_SIM3G_H_ */


