/*
 * app_sim3g.h
 *
 *  Created on: Nov 22, 2019
 *      Author: VAIO
 */


#ifndef APP_SIM3G_H_
#define APP_SIM3G_H_


enum SIM3G_STATE{
	SIM3G_STATUS = 0,
	POWER_ON_SIM3G,
	POWER_OFF_SIM3G,
	DEFINE_PDP_CONTEXT,
	SET_AUTHENTICATION_PARAMETER,
	SET_PDP_CONTEXT_NUMBER,
	PDP_CONTEXT_ACTIVATION,
	PDP_CONTEXT_DEACTIVATION,
	RECEIVE_DATA_LENGTH_OPTION,
	RECEIVE_DATA_ADDRESS_OPTION,
	ADJUST_NUMBER_OF_RETRANSMISSION,
	ESTABLISH_CONNECTION,
	SEND_DATA,
	DISCONNECT_CONNECTION
};


#endif /* APP_SIM3G_H_ */


